apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: webservice
  name: webservice
  namespace: default
spec:
  containers:
  - image: webservice
    name: webservice
    imagePullPolicy: Never
    envFrom:
      - configMapRef:
          name: kafka-settings
      - secretRef:
          name: kafka-cred
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always